# -*- coding: utf-8 -*-
"""Self-contained robot model loader.

Reads a plain YAML robot asset (see ``config/robots/panda.yaml``, generated by
``tools/gen_robot_asset.py`` from the C++ compile-time model) and builds a
``prrtc.RobotModelBuilder``. This replaces the production
``_build_robot_model`` with a fully self-contained path: no external kinematics
library, ``CudaRobotModel``, or URDF parsing at runtime.

The YAML already stores the pRRTC-native layout the CUDA kernels expect
(row-major fixed transforms per joint, spheres grouped by joint index,
inclusive-end self-collision ranges), so the loader only has to:
  1. flatten the nested lists,
  2. derive the approx (one-bounding-sphere-per-joint) gate model, and
  3. populate the builder.

The approx helpers are ports of the production
``_build_approx_spheres`` / ``_build_approx_self_cc_ranges`` so the gate model
is bit-consistent with the validated production path.
"""

from collections import defaultdict
from pathlib import Path

import yaml

_DEFAULT_ASSET = (
    Path(__file__).resolve().parents[3] / "config" / "robots" / "panda.yaml"
)


def _build_approx_spheres(spheres_flat, sphere_to_joint, n_joints):
    """One bounding sphere per joint: centroid + max dist-to-surface.

    Port of the production ``_build_approx_spheres``. Returns
    ``(approx_spheres_flat, approx_sphere_to_joint)``.
    """
    joint_spheres = defaultdict(list)
    n_spheres = len(sphere_to_joint)
    for si in range(n_spheres):
        x = spheres_flat[si * 4 + 0]
        y = spheres_flat[si * 4 + 1]
        z = spheres_flat[si * 4 + 2]
        r = spheres_flat[si * 4 + 3]
        if r <= 0.0:
            continue
        joint_spheres[sphere_to_joint[si]].append((x, y, z, r))

    approx_flat = []
    approx_joints = []
    for j in range(n_joints):
        sph_list = joint_spheres.get(j, [])
        if not sph_list:
            continue
        cx = sum(s[0] for s in sph_list) / len(sph_list)
        cy = sum(s[1] for s in sph_list) / len(sph_list)
        cz = sum(s[2] for s in sph_list) / len(sph_list)
        max_r = 0.0
        for x, y, z, r in sph_list:
            dist = ((x - cx) ** 2 + (y - cy) ** 2 + (z - cz) ** 2) ** 0.5 + r
            max_r = max(max_r, dist)
        approx_flat.extend([cx, cy, cz, max_r])
        approx_joints.append(j)
    return approx_flat, approx_joints


def _build_approx_self_cc_ranges(full_self_cc_ranges, sphere_to_joint,
                                 approx_sphere_to_joint):
    """Approx self-collision ranges mirroring full ranges at joint level.

    Port of the production ``_build_approx_self_cc_ranges``. The kernel uses
    the approx pass as a gate for the detailed check, so this must cover every
    joint pair present in the full ranges. Returns a flat inclusive-end list.
    """
    if not full_self_cc_ranges:
        return []

    joint_to_approx = {}
    for ai, j in enumerate(approx_sphere_to_joint):
        joint_to_approx[j] = ai

    approx_pairs = defaultdict(set)
    n_entries = len(full_self_cc_ranges) // 3
    for e in range(n_entries):
        si = full_self_cc_ranges[e * 3 + 0]
        start = full_self_cc_ranges[e * 3 + 1]
        end = full_self_cc_ranges[e * 3 + 2]
        ji = sphere_to_joint[si]
        for sj in range(start, end + 1):
            jj = sphere_to_joint[sj]
            if ji == jj:
                continue
            ai = joint_to_approx.get(ji)
            aj = joint_to_approx.get(jj)
            if ai is None or aj is None:
                continue
            approx_pairs[ai].add(aj)
            approx_pairs[aj].add(ai)

    result = []
    for ai in sorted(approx_pairs.keys()):
        partners = sorted(p for p in approx_pairs[ai] if p > ai)
        if not partners:
            continue
        range_start = partners[0]
        range_end = partners[0]
        for p in partners[1:]:
            if p == range_end + 1:
                range_end = p
            else:
                result.extend([ai, range_start, range_end])
                range_start = p
                range_end = p
        result.extend([ai, range_start, range_end])
    return result


def load_robot_asset(path=None):
    """Parse the robot YAML into flat host arrays (no prrtc dependency).

    Returns a dict with the pRRTC-native fields plus the derived approx model.
    Useful on its own for the equivalence test.
    """
    path = Path(path) if path is not None else _DEFAULT_ASSET
    with open(path, "r") as f:
        doc = yaml.safe_load(f)

    n_dof = int(doc["n_dof"])
    n_joints = int(doc["n_joints"])
    joint_types = [int(v) for v in doc["joint_types"]]

    fixed_transforms = []
    for row in doc["fixed_transforms"]:
        fixed_transforms.extend(float(v) for v in row)
    assert len(fixed_transforms) == n_joints * 16, (
        len(fixed_transforms), n_joints * 16)

    spheres_flat = []
    for s in doc["spheres"]:
        spheres_flat.extend(float(v) for v in s)
    sphere_to_joint = [int(v) for v in doc["sphere_to_joint"]]
    assert len(spheres_flat) == len(sphere_to_joint) * 4

    self_cc_ranges_flat = []
    for c in doc["self_cc_ranges"]:
        self_cc_ranges_flat.extend(int(v) for v in c)

    joint_lower = [float(v) for v in doc["joint_lower"]]
    joint_upper = [float(v) for v in doc["joint_upper"]]

    # Kinematic tree topology. Older assets predate these fields; fall back to
    # the serial chain so they keep loading (and behaving) unchanged.
    joint_parents = [int(v) for v in doc.get(
        "joint_parents", [max(i - 1, 0) for i in range(n_joints)])]
    joint_id_to_dof = [int(v) for v in doc.get(
        "joint_id_to_dof", [i - 1 for i in range(n_joints)])]
    t_memory_idx = [int(v) for v in doc.get(
        "t_memory_idx", [0] + [1] * (n_joints - 1))]
    dfs_order = [int(v) for v in doc.get("dfs_order", list(range(n_joints)))]
    for nm, arr in (("joint_parents", joint_parents),
                    ("joint_id_to_dof", joint_id_to_dof),
                    ("t_memory_idx", t_memory_idx),
                    ("dfs_order", dfs_order)):
        assert len(arr) == n_joints, (nm, len(arr), n_joints)

    approx_spheres_flat, approx_sphere_to_joint = _build_approx_spheres(
        spheres_flat, sphere_to_joint, n_joints)
    approx_self_cc_ranges_flat = _build_approx_self_cc_ranges(
        self_cc_ranges_flat, sphere_to_joint, approx_sphere_to_joint)

    return {
        "name": doc.get("name", "robot"),
        "n_dof": n_dof,
        "n_joints": n_joints,
        "joint_types": joint_types,
        "fixed_transforms": fixed_transforms,
        "spheres_flat": spheres_flat,
        "sphere_to_joint": sphere_to_joint,
        "self_cc_ranges_flat": self_cc_ranges_flat,
        "joint_lower": joint_lower,
        "joint_upper": joint_upper,
        "joint_parents": joint_parents,
        "joint_id_to_dof": joint_id_to_dof,
        "t_memory_idx": t_memory_idx,
        "dfs_order": dfs_order,
        "n_t_slots": max(t_memory_idx) + 1,
        "approx_spheres_flat": approx_spheres_flat,
        "approx_sphere_to_joint": approx_sphere_to_joint,
        "approx_self_cc_ranges_flat": approx_self_cc_ranges_flat,
    }


def build_robot_model(path=None):
    """Load the asset and return a populated ``prrtc.RobotModelBuilder``.

    The builder — not the device ``RobotModel`` — is the object the solve
    entry points (``solve_scene``, ``mitstar_solve_scene``, ...) accept; each
    calls ``build_on_device()`` internally. We materialise the device tensors
    eagerly via ``builder.build()`` so allocation failures surface at
    initialisation rather than on the first solve, then hand the builder back.

    Requires the compiled ``prrtc`` pybind module on ``PYTHONPATH``.
    """
    import prrtc

    asset = load_robot_asset(path)

    builder = prrtc.RobotModelBuilder()
    builder.n_dof = asset["n_dof"]
    builder.n_joints = asset["n_joints"]
    builder.fixed_transforms = asset["fixed_transforms"]
    builder.joint_types = asset["joint_types"]
    builder.spheres_flat = asset["spheres_flat"]
    builder.sphere_to_joint = asset["sphere_to_joint"]
    builder.self_cc_ranges_flat = asset["self_cc_ranges_flat"]
    builder.approx_spheres_flat = asset["approx_spheres_flat"]
    builder.approx_sphere_to_joint = asset["approx_sphere_to_joint"]
    builder.approx_self_cc_ranges_flat = asset["approx_self_cc_ranges_flat"]
    builder.joint_lower = asset["joint_lower"]
    builder.joint_upper = asset["joint_upper"]
    # Kinematic tree topology. A prrtc build that predates the tree-walking FK
    # has no such fields; fall back to its serial-chain behaviour rather than
    # failing, but refuse to silently mis-plan for a robot that actually
    # branches (the serial FK would place the second arm on the wrong parent).
    if hasattr(builder, "joint_parents"):
        builder.joint_parents = asset["joint_parents"]
        builder.joint_id_to_dof = asset["joint_id_to_dof"]
        builder.t_memory_idx = asset["t_memory_idx"]
        builder.dfs_order = asset["dfs_order"]
    else:
        n_joints = asset["n_joints"]
        serial = ([i - 1 for i in range(n_joints)] == asset["joint_id_to_dof"]
                  and [max(i - 1, 0) for i in range(n_joints)] == asset["joint_parents"]
                  and list(range(n_joints)) == asset["dfs_order"])
        if not serial:
            raise RuntimeError(
                f"robot asset {asset['name']!r} has a branching kinematic tree, "
                "but the compiled prrtc module predates tree FK support "
                "(RobotModelBuilder.joint_parents is missing). Rebuild the "
                "extension before planning for this robot.")

    builder.build()  # materialise device tensors now (idempotent)
    return builder
